/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FakeBTC } from './FakeBTC.js';
export * as factories from './factories/index.js';
export { FakeBTC__factory } from './factories/FakeBTC__factory.js';