/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BTC } from './BTC.js';
export * as factories from './factories/index.js';
export { BTC__factory } from './factories/BTC__factory.js';